#ifndef SETTINGS_H
#define SETTINGS_H

#define NUMBEROFDIMENSIONS 2

#define NUMBEROFCELLSX 600
#define NUMBEROFCELLSY 600

#define WORKTIME 50

#define MAXNUMBEROFNEURONS 10
#define MAXNUMBEROFGROWTHCONES 16

#define INTERACTION00 ( 0.0 )
#define INTERACTION01 ( 1.0 )
#define INTERACTION10 ( 1.0 )
#define INTERACTION11 ( 0.0 )
#define NUMBEROFNEURONTYPES 2
//#define DIFFUSIONVISIBLE

//#define MEMORYCHECKING
//#define STEPBYSTEP
//#define NEUROGENESIS

#define TRACESON
#define TRACEINFILE
/* TODO: create trace groups */
//#define CELLSTACKTRACES
//#define GROWTHCONETRACES
//#define CONNECTIONTRACES
//#define BRANCHINGTRACES

//#define STATISTICSON
#ifdef STATISTICSON
#define LENGTHSTATISTICS
#define ENVIRONMENTSTATISTICS
#define CONNECTIVITYGRAPHSTATISTICS
#endif

#define LOGFILENAME     "stat/log.txt"
#define LENGTHSTATISTICSFILE  "stat/length.txt"
#define ENVIRONMENTSTATISTICSFILE  "stat/environment.txt"
#define CONNECTIVITYGRAPHSTATISTICSFILE  "stat/connectivitygraph.txt"
#define CONNECTIVITYGRAPHSTATISTICSRATE 5

//#define CONNECTIVITYTEST1
#ifdef CONNECTIVITYTEST1
#undef MAXNUMBEROFNEURONS
#define MAXNUMBEROFNEURONS 2
#endif

#define AXONGROWTH
#define DENDRITEGROWTH
#endif